### PR TITLE
Added Unstop as a Partner

### PR DESCRIPTION
**Pull request by manosrija-nasrin**
Changes mainly to Sponsor section
- Added Unstop as a Partner
- Added Partner categories
- Cropped ACM India logo
- Reduced the size of the Unstop and Beeceptor logos

There are duplicate commits in this PR that have been merged already.

**Note:** Discord link to be added soon. Merge when the link is available.

### CODE REVIEW

**Comment by manosrija-nasrin** [comment]
Checks seem to be failing. The live demo is working fine on my machine. Pending further review.

**Review by AdityaMayukhSom — CHANGES_REQUESTED** [review]
Use the logo from [here](https://event.india.acm.org/pic/home/), download the SVG and convert it to PNG or JPG if necessary, otherwise SVG is more suitable for web.

Try to refrain from changing component names and adding new files unless necessary, also try to use jsDoc for typing props if possible. refer to [dark-theme/SectionTitle.jsx](https://github.com/AdityaMayukhSom/synchronicity-s1/blob/dark-theme/src/components/lib/SectionTitle.jsx)

**Comment by manosrija-nasrin** [comment]
Added JSDoc comments for props. Added SVG logo for ACM India, removed JPEG file. Added `smooth-scroll` behaviour to global `main.css`. 
Changes made to Sponsors structure - Added a `descriptor` property for Sponsor subtype.

```js
Sponsor.propTypes = {
  name: PropTypes.string,
  descriptor: PropTypes.string,
  sponsorWebsiteURL: PropTypes.string,
  sponsorLogoURL: PropTypes.string.isRequired,
};
```

Still not sure what is failing the checks. Maybe I can get the detailed error log?

**Comment by manosrija-nasrin** [comment]
Turns out there was a problem with the filename casing. "../partners.js" was erroneously imported as "../Partners.js". 

Fixed the typo. Checks are passing.

**Review by AdityaMayukhSom — APPROVED** [review]

**Pull request merged**
